package com.rivigo.riconet.core.dto;

public enum VendorContractStatus {
    CREATED,
    PENDING_LEGAL_CHECK,
    PENDING_OPERATIONS_APPROVAL,
    PENDING_EXPENSE_OWNER_APPROVAL,
    PENDING_FINANCE_APPROVAL,
    PENDING_LEGAL_APPROVAL,
    PENDING_SIGNED_CONTRACT_UPLOAD,
    PENDING_CONTRACT_VERIFICATION,
    APPROVED,
    REJECTED,
    ACTIVE,
    DISCARDED,
    EXPIRED;
}
