package com.rivigo.riconet.core.enums;

public enum CnBlockUnblockEventName {
  COLLECTION_CHEQUE_BOUNCE,
  CN_COLLECTION_CHEQUE_BOUNCE_TICKET_CLOSED,
  CN_SHORTAGE_RESOLUTION,
  BLOCK_UNBLOCK_PARTIAL_DELIVERY,
}
