package com.rivigo.riconet.core.enums;

public enum EventName {
  CN_COMPLETION_ALL_INSTANCES,
  CN_RECEIVED_AT_OU,
  CN_LOADED,
  CN_STATUS_CHANGE_FROM_RECEIVED_AT_OU,
  CN_CNOTE_TYPE_CHANGED_FROM_NORMAL,

  PICKUP_CANCELLATION,
  PICKUP_COMPLETION,
  PICKUP_REACHED_AT_CLIENT_WAREHOUSE,
  PICKUP_ASSIGNMENT,

  CN_DRS_DISPATCH,
  CN_DELIVERY,
  CN_DELIVERY_LOADED,
  CN_DELETED,
  CN_TRIP_DISPATCHED,
  CN_PAYMENT_HANDOVER_COMPLETED,
  CN_STALE,

  COLLECTION_CHEQUE_BOUNCE,

  CN_CNOTE_CHANGE,
  CN_DEPS_CREATION,
  CN_DEPS_CREATION_FROM_CONSIGNMENT_HISTORY,

  /** TicketingFieldName Event * */
  TICKET_CREATION,
  TICKET_ASSIGNEE_CHANGE,
  RTO_TICKET_ASSIGNEE_CHANGE,
  TICKET_STATUS_CHANGE,
  TICKET_ESCALATION_CHANGE,
  TICKET_CC_NEW_PERSON_ADDITION,
  TICKET_ACTION,
  TICKET_SEVERITY_CHANGE,
  TICKET_COMMENT_CREATION,

  /** Datastore address cleanup * */
  CONSIGNMENT_EWAYBILL_METADATA_CREATION_ADDRESS_CLEANUP,
}
