package com.rivigo.riconet.core.enums;

public enum TransactionManagerEventNames {
  CN_CREATION_COLLECTIONS,
  CN_EDIT_COLLECTIONS,
  CN_PAYMENT_COLLECTIONS,
  CN_HANDOVER_COMPLETED_COLLECTIONS,
  NORMAL_TO_NORMAL_TO_PAY_CHANGE_COLLECTIONS,
  NORMAL_TO_PAY_TO_NORMAL_CHANGE_COLLECTIONS,
  PAID_TO_TO_PAY_CHANGE_COLLECTIONS,
  PAYMENT_CHANGE_TO_BANK_TRANSFER_COLLECTIONS,
  CHEQUE_BOUNCE_BANK_TRANSFER_COLLECTIONS,
  DEPOSIT_SLIP_CREATION_COLLECTIONS,
  DEPOSIT_SLIP_CANCELLATION_COLLECTIONS,
  RETURN_MONEY_COMPLETED_COLLECTIONS,
  CN_INVALIDATION_COLLECTIONS,
  TO_PAY_CAPTAIN_ASSIGN_COLLECTIONS,
  BANK_TRANSFER_APPROVAL_COLLECTIONS,
  BANK_TRANSFER_REJECTION_COLLECTIONS;
}
