package com.rivigo.riconet.core.enums;

public enum TransactionManagerEventNames {
  CN_CREATION_COLLECTIONS,
  CN_PAYMENT_COLLECTIONS,
  CN_HANDOVER_COMPLETED_COLLECTIONS,
  CN_EDIT_COLLECTIONS,
  NORMAL_TO_NORMAL_TO_PAY_CHANGE,
  PAYMENT_CHANGE_TO_BANK_TRANSFER,
  CHEQUE_BOUNCE_BANK_TRANSFER
}
