package com.rivigo.riconet.core.enums;

public enum ZoomPropertyName {
  PRIORITY_TICKET_TYPE,
  AUTOCLOSABLE_PRIORITY_TICKET_TYPE,

  // Deps
  DEPS_EMAIL_TESTING,
  DEPS_EMAIL_ENABLED,
  SHORTAGE_NOTIFICATION_SUBJECT,
  SHORTAGE_NOTIFICATION_TEMPLATE,

  DOCUMENT_ISSUE_EMAIL_ENABLED,
  DOCUMENT_ISSUE_NOTIFICATION_SUBJECT,
  DOCUMENT_ISSUE_NOTIFICATION_TEMPLATE,
  DOCUMENT_ISSUE_BUFFER_MINUTES,

  TESTING,
  BOOLEAN_TESTING,

  PICKUP_REACHED_SMS_STRING,
  PICKUP_DELAYED_SMS_STRING,
  PICKUP_ASSIGNED_TO_USER_SMS_STRING,
  PICKUP_ASSIGNED_BP_USER_SMS_STRING,
  PICKUP_CREATED_SMS_STRING,
  PICKUP_DELAY_NOTIFICATION_SECONDS,
  DEFAULT_SMS_NUMBER,
  PICKUP_NOTIFICATION_ALLOWED_LOCATIONS,
  INTEGER_TESTING,
  APPOINTMENT_NOTIFICATION_ENABLED,
  APPOINTMENT_DELIVERED_LATE_SAME_DAY_SUBJECT,
  APPOINTMENT_DELIVERED_LATE_SAME_DAY_EMAIL,
  APPOINTMENT_DELIVERED_LATE_DIFFERENT_DAY_SUBJECT,
  APPOINTMENT_MISSED_SUBJECT,
  APPOINTMENT_MISSED_EMAIL,
  APPOINTMENT_MISSED_SUMMARY_SUBJECT,
  APPOINTMENT_MISSED_SUMMARY_EMAIL,
  APPOINTMENT_WRONG_UNDELIVERED_MARKED_SUBJECT,
  APPOINTMENT_WRONG_UNDELIVERED_MARKED_EMAIL,
  APPOINTMENT_NOT_OFD_EMAIL,
  APPOINTMENT_NOT_OFD_SUBJECT,
  RETAIL_COD_CN_CREATION_CONSIGNEE_SMS_STRING,
  RETAIL_COD_CN_CREATION_CONSIGNOR_SMS_STRING,
  RETAIL_PREPAID_CN_CREATION_CONSIGNOR_SMS_STRING,
  RETAIL_PREPAID_CN_CREATION_CONSIGNEE_SMS_STRING,
  RETAIL_PREPAID_CN_UPDATE_CONSIGNEE_SMS_STRING,
  RETAIL_PREPAID_CN_UPDATE_CONSIGNOR_SMS_STRING,
  RETAIL_COD_CN_UPDATE_CONSIGNEE_SMS_STRING,
  RETAIL_COD_CN_UPDATE_CONSIGNOR_SMS_STRING,
  RETAIL_COD_DRS_DISPATCH_CONSIGNEE_SMS_STRING,
  RETAIL_COLLECTION_CREATION_USER_SMS_STRING,
  RETAIL_COLLECTION_CREATION_BP_SMS_STRING,
  RETAIL_HANDOVER_USER_SMS_STRING,
  RETAIL_HANDOVER_BP_SMS_STRING,
  RETAIL_COLLECTION_CREATION_BP_CAPTAIN_SMS_STRING,
  APPOINTMENT_DELIVERED_LATE_DIFFERENT_DAY_EMAIL,
  ZOOM_COMMUNICATION_DND_START_TIME,
  ZOOM_COMMUNICATION_DND_END_TIME,
  BF_PICKUP_CHARGE_PER_KG

  /** Rule engine consttants */
  ,
  MINIMUM_NUMBER_OF_CN_REQUIRED,
  MINIMUM_PICKUP_CHARGES_FOR_BF,
  REQUIRED_CLIENT_TYPE,
  MAXIMUM_VOLUME_ALLOWED_WITHOUT_QC,
  MAXIMUM_VOLUME_WEIGHT_RATIO_ALLOWED_WITHOUT_QC,
  MAXIMUM_VOLUME_WITH_RATIO_CONSTRAINT_QC,
  MAXIMUM_RATIO_WITH_VOLUME_CONSTRAINT_QC,
  MAXIMUM_BOXES_WITH_WEIGHT_EQUALS_BOXES_QC,
  WEIGHT_TOTAL_BOXES_DIFF_QC,
  QC_DIMENSION_VALUE,
  MANDATORY_QC_VALIDATION_CN_LIMIT,

  QC_BLOCKER_EMAIL_SUBJECT,
  QC_BLOCKER_EMAIL_BODY,
  QC_BLOCKER_EMAIL_SUBJECT_RETAIL,
  QC_BLOCKER_EMAIL_BODY_RETAIL,
  EMAIL_ENABLED,
  DEFAULT_EMAIL_IDS,
  QC_BLOCKER_TICKET_EXPIRY_HOURS,

  QC_MODEL_API_TIMEOUT,

  STG_NOTIF_ALLOWED_APP_USER_IDS,

  // Online Payments
  DND_EXEMPTED_SMS_EVENTS
}
