package com.rivigo.riconet.core.enums;

public enum ZoomCommunicationFieldNames {
  CNOTE,
  OLD_CNOTE,
  CLIENT_ID,
  LOCATION_ID,
  TO_LOCATION_ID,
  CONSIGNMENT_ID,
  STATUS,
  INSTRUMENT_NUMBER,
  DRAWEE_BANK,
  AMOUNT,
  DEPOSIT_DATE,
  PAYMENT_MODE,
  ORIGIN_FIELD_USER_NAME,
  ORIGIN_FIELD_USER_PHONE,
  DESTINATION_FIELD_USER_NAME,
  DESTINATION_FIELD_USER_PHONE,
  CREATED_BY,
  CONSIGNER_ADDRESS,
  CONSIGNEE_ADDRESS,
  ORGANIZATION_ID,
  PICK_UP_ID,
  USER_ID,
  USER_EMAIL,
  TASK_ID,
  FROM_LOCATION_ID,
  LAST_UPDATED_BY_ID,
  TICKET_ENTITY_ID,
  PARENT_TASK_ID,
  TASK_TYPE,
  ACTION_NAME,
  ACTION_VALUE,

  STALE_CATEGORY,
  TYPE_ID,
  SHOP_FLOOR_ENABLED,
  OU_CODE;

  public enum Reason {
    REASON,
    SUB_REASON
  }
}
