package com.rivigo.riconet.core.enums;

public enum ZoomCommunicationFieldNames {
  CNOTE,
  LOCATION_ID,
  CONSIGNMENT_ID,
  STATUS,
  INSTRUMENT_NUMBER,
  DRAWEE_BANK,
  AMOUNT,
  DEPOSIT_DATE,
  PAYMENT_MODE,
  ORIGIN_FIELD_USER_NAME,
  ORIGIN_FIELD_USER_PHONE,
  DESTINATION_FIELD_USER_NAME,
  DESTINATION_FIELD_USER_PHONE,
  CREATED_BY,
  CONSIGNER_ADDRESS,
  CONSIGNEE_ADDRESS;

  public enum Reason {
    REASON,
    SUB_REASON
  }
}
