package com.rivigo.riconet.core.enums;

public enum ZoomCommunicationFieldNames {
  CNOTE,
  OLD_CNOTE,
  CLIENT_ID,
  LOCATION_ID,
  CONSIGNMENT_ID,
  STATUS,
  INSTRUMENT_NUMBER,
  DRAWEE_BANK,
  AMOUNT,
  DEPOSIT_DATE,
  PAYMENT_MODE,
  ORIGIN_FIELD_USER_NAME,
  ORIGIN_FIELD_USER_PHONE,
  DESTINATION_FIELD_USER_NAME,
  DESTINATION_FIELD_USER_PHONE,
  CREATED_BY,
  CONSIGNER_ADDRESS,
  CONSIGNEE_ADDRESS,
  ORGANIZATION_ID,
  FROM_LOCATION_ID,
  LAST_UPDATED_BY_ID,
  PICK_UP_ID,
  ENTITY_ID,
  TYPE_ID;

  public enum Reason {
    REASON,
    SUB_REASON
  }
}
